
server:
  port: 8084

jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-gateway:8761/eureka
