# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-slim
# Install curl
RUN apt-get update && apt-get install -y curl
# Create directory for catalog-service
RUN mkdir /app
# Copy the jar file for catalog-service into the container
COPY catalog-service/build/libs/catalog-service-0.0.1-SNAPSHOT.jar /app/catalog-service.jar
# Expose the necessary port
EXPOSE 8084

ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_LIFETIME=${JWT_LIFETIME}
# Start catalog-service
CMD ["java", "-jar", "/app/catalog-service.jar"]