services:
  eureka-gateway:
    image: dmitriy2028/eureka-gateway
    ports:
      - "8761:8761"
      - "8765:8765"

  auth-user-cart:
    image: dmitriy2028/auth-user-cart
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"

  catalog:
    image: dmitriy2028/catalog
    ports:
      - "8084:8084"