services:
  eureka-gateway:
    image: dmitriy2028/teamchallenge-eureka-gateway
    container_name: eureka-gateway
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "8761:8761"
      - "8765:8765"
    networks:
      - eureka-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '200M'
        reservations:
          cpus: '0.2'
          memory: '200M'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/actuator/health"]
      interval: 20s
      retries: 20
      start_period: 60s
      timeout: 20s

  auth-user-cart:
    image: dmitriy2028/teamchallenge-auth-user-cart
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - eureka-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '400M'
        reservations:
          cpus: '0.4'
          memory: '400M'
    depends_on:
      eureka-gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      retries: 40
      start_period: 240s
      timeout: 30s

  catalog:
    image: dmitriy2028/teamchallenge-catalog
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "8084:8084"
    networks:
      - eureka-network
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '150M'
        reservations:
          cpus: '0.15'
          memory: '150M'
    depends_on:
      auth-user-cart:
        condition: service_healthy

networks:
  eureka-network:
    driver: bridge