# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-slim
# Install curl
RUN apt-get update && apt-get install -y curl
# Create directories for eureka-server and api-gateway
RUN mkdir /app
# Copy the jar files for eureka-server and api-gateway into the container
COPY eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar /app/eureka-server.jar
COPY api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway.jar
# Expose the necessary ports
EXPOSE 8761
EXPOSE 8765

ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_LIFETIME=${JWT_LIFETIME}
# Start eureka-server and api-gateway
CMD ["sh", "-c", "java -jar /app/eureka-server.jar & java -jar /app/api-gateway.jar"]
