services:
  teamchallenge-all:
    image: dmitriy2028/teamchallenge-all
    container_name: eureka-gateway
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "8761:8761"
      - "8765:8765"
