services:
  eureka-gateway:
    image: dmitriy2028/eureka-gateway
    container_name: eureka-gateway
    ports:
      - "8761:8761"
      - "8765:8765"
    networks:
      - eureka-network

  auth-user-cart:
    image: dmitriy2028/auth-user-cart
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - eureka-network

  catalog:
    image: dmitriy2028/catalog
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8084:8084"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge