jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cq33sucs1f4s73f8409g-a.frankfurt-postgres.render.com/teamchallenge_k3zv
    username: teamchallenge_user
    password: zF6CNIAm08bu3ihy3kjRukkxMtDMJBuV

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
