jwt:
  secret: System.getenv("JWT_SECRET")
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: System.getenv("DATABASE_URL")
    username: System.getenv("DATABASE_USERNAME")
    password: System.getenv("DATABASE_PASSWORD")

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
