jwt:
  secret: ${JWT_SECRET}
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
