jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/teamChallenge
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
