
jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cont7vsf7o1s73frot1g-a.frankfurt-postgres.render.com/teamchallenge
    username: teamchallenge_user
    password: 7wQS07QVsKn04wo72XSGmKuNbOiDDhYj
    hikari:
      connection-init-sql: SET NAMES 'UTF8'
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
      encoding: UTF-8


logging:
  level:
    org:
      springframework:
        security=DEBUG:
