jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32768/teamChallenge
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml


logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
