
jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cont7vsf7o1s73frot1g-a.frankfurt-postgres.render.com/teamchallenge
    username: teamchallenge_user
    password: 7wQS07QVsKn04wo72XSGmKuNbOiDDhYj

logging:
  level:
    org:
      springframework:
        security=DEBUG:
