jwt:
  secret: ${JWT_SECRET}
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml

aws:
  s3:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET_NAME}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG
