
server:
  port: 8083

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

spring:
  application:
    name: cart-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-gateway:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

