
server:
  port: 8083

jwt:
  secret: as542d54fkja656s7h6ndfjas1241234kdnsadiojfkjasdk1123rjkj34
  lifetime: 7d

spring:
  application:
    name: cart-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32768/teamChallenge
    username: postgres
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

