name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Stop the old app on EC2
        run: pkill -f 'jar server-1.jar

      - name: Delete the old JAR file and output.log on EC2
        run: rm /home/ec2-user/downloads/server-1.jar /home/ec2-user/downloads/output.log

      - name: Copy the new JAR file from S3 to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: aws s3 cp s3://$S3_BUCKET/deploy/server-1.jar /home/ec2-user/downloads/server-1.jar

      - name: Restart the application
        run: nohup java -jar /home/ec2-user/downloads/server-1.jar > /home/ec2-user/downloads/output.log 2> /home/ec2-user/downloads/errors.log &