name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete the old JAR file and output.log on EC2
        run: rm -f /downloads/server-1.jar /downloads/output.log

      - name: Copy the new JAR file from S3 to EC2
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: aws s3 cp s3://$S3_BUCKET/deploy/server-1.jar /downloads/server-1.jar

      - name: Restart the application
        run: nohup java -jar /downloads/server-1.jar > /downloads/output.log 2>&1 &