name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          AWS_EC2_INSTANCE_IDS: ${{ secrets.AWS_EC2_INSTANCE_IDS }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          # Delete the old JAR file and output.log on EC2
          aws ssm send-command \
            --instance-ids "${AWS_EC2_INSTANCE_IDS}" \
            --document-name "AWS-RunShellScript" \
            --comment "Clean up old application files" \
            --parameters commands="rm -f /downloads/server-1.jar /downloads/output.log" \
            --region eu-central-1
          
          # Copy the new JAR file from S3 to EC2
          aws ssm send-command \
            --instance-ids "${AWS_EC2_INSTANCE_IDS}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy new version of application" \
            --parameters commands="aws s3 cp s3://$S3_BUCKET/deploy/server-1.jar /downloads/server-1.jar" \
            --region eu-central-1
          
          # Restart the application
          aws ssm send-command \
            --instance-ids "${AWS_EC2_INSTANCE_IDS}" \
            --document-name "AWS-RunShellScript" \
            --comment "Start application" \
            --parameters commands="nohup java -jar /downloads/server-1.jar > /downloads/output.log 2>&1 &" \
            --region eu-central-1